
```{r}
library("tseriesChaos", lib.loc="C:/Users/ignac/anaconda3/envs/rstudio/lib/R/library")
require(scatterplot3d)

library("dplyr", lib.loc="C:/Users/ignac/anaconda3/envs/rstudio/lib/R/library")


library("dplyr", lib.loc="C:/Users/ignac/anaconda3/envs/rstudio/lib/R/library")

library(readr)
```

```{r}
library(readr)
BE_cases <- read_csv("C:/Users/ignac/OneDrive - Universidad de Chile/Escritorio/Modelamietno Matematico/Chaos-Presence-SARS-CoV-II/BE_cases")

BE_cases = BE_cases[[1]]

windows()
lm <- 40
mutual_BE_cases = mutual(BE_cases, lag.max=lm)

# Lo pasamos a csv para trabajar en python

df <- data.frame(mutual_BE_cases = as.vector(mutual_BE_cases))

write.csv(df,"C:\\Users\\ignac\\OneDrive - Universidad de Chile\\Escritorio\\Modelamietno Matematico\\Chaos-Presence-SARS-CoV-II\\data_para_R\\AMI_BE.csv", row.names = FALSE)

```

```{r}
# Veamos una estimacion de la Theiler Window

library("nonlinearTseries", lib.loc="C:/Users/ignac/anaconda3/envs/rstudio/lib/R/library")

windows()
require(nonlinearTseries)
spaceTimePlot(time.series=BE_cases,embedding.dim=3,time.lag=5,
              time.step=1,number.time.steps=50, numberPercentages=10,do.plot=TRUE,
              main="",xlab="Separation in time",ylab="Separation in space")
# da 13

```

```{r}
# Calculamos la dimension con FNN

windows()
m.max<- 6 # embedding dimensions: BEom 1 to m_max
d<- 5 # tentative time delay (see below)
tw<- 13 # Theiler window
rt<- 20 # escape factor
eps<- sd(BE_cases) # neighbourhood diameter
fn_BE_cases <- false.nearest(BE_cases,m.max,d,tw,rt,eps)
fn_BE_cases


plot(fn_BE_cases)     # da una dimension de inmersion m = 3

```

```{r}
# Calculemos los MCLE

windows()
S_nu_BE_cases <- lyap_k(BE_cases,m=3,d=5,t=13,k=4,ref=300,s=50,eps=0.3)
plot(S_nu_BE_cases,xlab = expression(paste(nu)),ylab=expression(paste("S",(nu))))

S_nu_BE_cases = as.vector(S_nu_BE_cases)
```

```{r}
df_S_nu_BE <- data.frame(S_nu_BE_cases = as.vector(S_nu_BE_cases))

write.csv(df_S_nu_BE,"C:\\Users\\ignac\\OneDrive - Universidad de Chile\\Escritorio\\Modelamietno Matematico\\Chaos-Presence-SARS-CoV-II\\data_para_R\\S_nu_BE.csv", row.names = FALSE)
```


